### ISSUE TITLE
Reorganize code

### ISSUE THREAD

**Issue by malihass** [NREL/BioReactorDesign#15]
- [x] add setup #22
- [x] Swap json for yaml #22
- [x] See if we need the constraint on scipy version #22
- [x] Check which os to run on #22
- [x] Make sure ci passes #22
- Modules
  - Meshing
    - [x] block cylindrical meshing #22
    - [x] stl meshing #22
    - [x] Stir tank   #22
    - [x] Airlift reactor (use yaml for input) in `/bird/meshing` (follow example of stir tank reactor) then add an interface in `applications/`(also follow the stir tank example) #89 
  - Inverse modeling
    - [x] NN Surrogate bayesian calibration #22
  - Openfoam solvers
    - [x] Multiphase models: Grace, Higbie, (efficiency models) #22 
    - [x] Applications: BDOfoam (multiphase Euler + sub cycling chemistry for microbial reactions)  `OFsolvers/applications`
  - Case
     - [x] Flat panel reactors  `papers/` #114 
     - [x] Loop reactor  `papers/`
     - [x] BDOfoam  `papers/`
  - Post processing
    - [x] Get rid of plotsUtil in favor of the prettyPlot package  #22 
    - [x] Early prediction  #22 
    - [x] conditional mean #22 
    - [x] pv script for gh, concentration and outlet composition `bird/postProcess` #100
  - Pre processing
     - [x] Surf 2 patch utils #27
