### ISSUE TITLE
Missing OF9 tutorial for Stir tank and Bubble column

### ISSUE THREAD

**Issue by malihass** [NREL/BioReactorDesign#29]
- [x] bubble column with fancy sparger #31 
- [x] coflowing bubble column  #31 
- [x] Stir tank case #31
